### ISSUE TITLE
pull requests aren't clickable

### ISSUE THREAD

**Issue by makc** [threejsworker/threejsworker#13]
there is also this
![screen shot 2015-10-16 at 2 31 32](https://cloud.githubusercontent.com/assets/242577/10531076/137fcc6a-73ae-11e5-827d-d7d6038be1d4.png)
when you try.

**Comment by gero3** [comment]
In which browser is this??

**Comment by makc** [comment]
firefox nightly I think

**Comment by gero3** [comment]
This is now fixed in the new version that is online: http://ci.threejs.org/pullrequests.html.
